name: Build + Deploy event-generator

on:
  push:
    branches:
      - main
    paths:
      - 'lambdas/event-generator/**'

jobs:
  build-backend:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: 'lambdas/event-generator/yarn.lock'

      - name: Install dependencies
        run: yarn install
        working-directory: ./lambdas/event-generator

      - name: Test Lambda
        run: yarn test
        working-directory: ./lambdas/event-generator

      - name: Zip Lambda
        run: zip -rj lambda_package.zip ./lambdas/event-generator/src

      - name: Configure AWS Credentials for Lambda Access
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_LAMBDA_ROLE }}
          role-duration-seconds: 900
          aws-region: eu-west-2

      - name: Deploy lambda
        run: |
          aws lambda update-function-code --function-name ${{ secrets.AWS_LAMBDA_PUB }} --zip-file fileb://lambda_package.zip
